### ISSUE TITLE
'collectionManager' or 'collectionsManager'

### ISSUE THREAD

**Issue by lifewcody** [phalcon/incubator#971]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

There are two difference instances of collection(s)Manager

> Provide output if related

```php

When using 'collectionManager'

Service 'collectionsManager' wasn't found in the dependency injection container
#0 [internal function]: Phalcon\Di->get('collectionsMana...', NULL)
#1 /my.app/vendor/phalcon/incubator-mongodb/src/Mvc/Collection.php(129): Phalcon\Di->getShared('collectionsMana...')
#2 /my.app/vendor/phalcon/incubator-mongodb/src/Mvc/Collection.php(784): Phalcon\Incubator\MongoDB\Mvc\Collection->__construct()
#3 /my.app/app/controllers/IndexController.php(42): Phalcon\Incubator\MongoDB\Mvc\Collection::find(Array)
#4 [internal function]: IndexController->indexAction()
#5 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(IndexController), 'indexAction', Array)
#6 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#7 /my.app/public/index.php(60): Phalcon\Mvc\Application->handle('/')

When using 'collectionsManager'

Service 'collectionManager' wasn't found in the dependency injection container
#0 [internal function]: Phalcon\Di->get('collectionManag...', NULL)
#1 /my.app/vendor/phalcon/incubator-mongodb/src/Mvc/Collection.php(1292): Phalcon\Di->getShared('collectionManag...')
#2 [internal function]: Phalcon\Incubator\MongoDB\Mvc\Collection->unserialize('a:10:{s:3:"_id"...')
#3 [internal function]: session_start()
#4 /my.app/app/config/services.php(146): Phalcon\Session\Manager->start()
#5 [internal function]: Closure->{closure}()
#6 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#7 [internal function]: Phalcon\Di->get('session', NULL)
#8 [internal function]: Phalcon\Di->getShared('session')
#9 /my.app/app/controllers/ControllerBase.php(76): Phalcon\Di\Injectable->__get('session')
#10 [internal function]: ControllerBase->beforeExecuteRoute(Object(Phalcon\Mvc\Dispatcher))
#11 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch()
#12 /my.app/public/index.php(60): Phalcon\Mvc\Application->handle('/')

```
> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details

* Phalcon Framework version: 4.1.0
* Phalcon Incubator version: compoer 1.0.1
* PHP Version: 7.4.27
* Operating System: Ubuntu 20.04
* Server: Nginx + FPM
* Other related info (Database, table schema): MongoDB

**Comment by Jeckerson** [comment]
Fixed in `phalcon/incubator-mongodb@v2.0.0`.

Now it is always in plural: `collectionsManager`
